[package]
name = "pallet-opf"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Optimist Project Funding - pallet allowing users to nominate projects to be funded, by locking their DOTS."
readme = "README.md"


[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true, default-features = false }
log = { workspace = true }
scale-info = { features = ["derive"], workspace = true , default-features = false }
frame-benchmarking = { optional = true, workspace = true , default-features = false }
frame-support = { workspace = true , default-features = false }
frame-system = { workspace = true , default-features = false }
sp-io = { workspace = true , default-features = false }
sp-runtime = { workspace = true , default-features = false }
sp-core = { workspace = true , default-features = false }

pallet-assets = { workspace = true, default-features = false }
pallet-balances = { workspace = true, default-features = false }
pallet-timestamp = { workspace = true, default-features = false }
pallet-sudo = { workspace = true, default-features = false }
pallet-transaction-payment = { workspace = true, default-features = false }
pallet-transaction-payment-rpc-runtime-api = { workspace = true, default-features = false }
pallet-conviction-voting = { workspace = true, default-features = false }
pallet-distribution = { workspace = true, default-features = false }

[features]
default = ["std"]
temporary = []
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"log/std",
	"scale-info/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-conviction-voting/std",
	"pallet-timestamp/std",
	"pallet-sudo/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-assets/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-balances/try-runtime",
	"sp-runtime/try-runtime",
]
